name: strive
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  dynamic_fonts: ^2.2.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/rec.png
    - assets/EventTwoIcon.png
    - assets/imgthee.png
    - assets/eventThreeimg.png
    - assets/eventthreeimgg.png
    - assets/refer.png
    - assets/referlo.png
  fonts:
    - family: agencyfb
      fonts:
        - asset: fonts/agencyfb.ttf
  
  

